# Generated by Django 2.1.2 on 2019-03-11 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190311_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todouser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
