# Generated by Django 2.1.2 on 2019-03-11 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190311_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='done',
            new_name='tododone',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='gshm',
            new_name='todogshm',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='thing',
            new_name='todothing',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='work_time',
            new_name='todoworktime',
        ),
        migrations.AlterField(
            model_name='todo',
            name='todouser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
