# Generated by Django 2.1.2 on 2019-03-11 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_todo_格式化秒'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='用户',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
