# Generated by Django 2.1.2 on 2019-03-11 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todothing', models.CharField(max_length=50)),
                ('tododone', models.BooleanField(default=False)),
                ('todoworktime', models.IntegerField(default=0)),
                ('todogshm', models.CharField(max_length=15)),
                ('todouser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
